# Generated by Django 6.0.1 on 2026-01-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_options_file_create_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at', '-created_at']},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
